version: '3'


services:
  app:
    build: .
    image: laracamp
    container_name: laracamp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/laracamp
    volumes:
      - .:/var/www/laracamp
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laracamp

      #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginxlaracamp
    restart: unless-stopped
    tty: true
    ports:
      - "2022:80"
    volumes:
      - .:/var/www/laracamp
      - ./storage:/etc/nginx/conf.d/
    networks:
      - laracamp

  db:
    image: mysql:5.7
    container_name: dblaracamp
    restart: always
    tty: true
    ports:
      - "2021:3306"
    volumes:
      - lbdata:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: laracamp
      MYSQL_ROOT_PASSWORD: laracamp
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laracamp


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmlaracamp
    links:
      - db
    restart: always
    ports:
      - 7000:80
    networks:
      - laracamp


# NETWORKS
networks:
  laracamp:
    driver: bridge


# VOLUME
volumes:
  lbdata:
    driver: local
